"""Type stubs for the turbo_xlsx PyO3 extension."""

from typing import Any

class TurboXlsxError(Exception):
    code: str
    message: str

class WorkbookWriter:
    def __init__(
        self, locale: str | None = ..., opts: dict[str, Any] | None = ...
    ) -> None: ...
    def start_sheet(self, sheet: dict[str, Any]) -> None: ...
    def write_row(self, row: dict[str, Any]) -> None: ...
    def write_rows_json(self, rows_json: str) -> None: ...
    def write_table(
        self, columns: list[dict[str, Any]], rows: Any
    ) -> None: ...
    def end_sheet(self) -> None: ...
    def finish(self) -> tuple[bytes, list[dict[str, str]]]: ...

def write(workbook: dict[str, Any], opts: dict[str, Any] | None = ...) -> bytes: ...
def write_full(
    workbook: dict[str, Any], opts: dict[str, Any] | None = ...
) -> tuple[bytes, list[dict[str, str]]]: ...
def write_from_json(
    input: str | dict[str, Any], opts: dict[str, Any] | None = ...
) -> bytes: ...
def write_rows(input: dict[str, Any], opts: dict[str, Any] | None = ...) -> bytes: ...
def create_writer(opts: dict[str, Any] | None = ...) -> WorkbookWriter: ...
